apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: java-3624-gitops
  description: This is GitOps manifest for java-3624   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: java-3624
    janus-idp.io/tekton: java-3624 
    backstage.io/kubernetes-id: java-3624 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:java-3624
