apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: java-3624
  janus-idp.io/tekton: java-3624
  backstage.io/kubernetes-id: java-3624
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: java-3624
resources:
- deployment.yaml
- route.yaml
- service.yaml
